# Examen Final - Mortalidad Materna


## Parte 3 - Análisis inicial (20 puntos)
- Nombre de los encabezados
- Muestra un DataFrame que contenga: Edad cumplida, Descripción del estado conyugal, Tamaño de localidad, Localidad de ocurrencia, Descrición de la localidad de ocurrencia
- ¿Cuántas edades diferentes tenían las madres cuando fallecieron? Obten los estadísticos para esta columna y los valores de las edades diferentes. 
- Imprime los valores de los años de defunción ¿ Existen datos que son lógicos, es decir, están correctos? 
- ¿Cuántos tipos de escolaridad existen? ¿Hay datos innecesarios o equivocados en la base de datos? 
- ¿Qué entidad tiene mayor número muertes? 


In [74]:
# Importamos paquetería

# Libreria
import pandas as pd

# Númerico
import numpy as np

# Gráficas
import matplotlib.pyplot as plt

In [84]:
# Cargamos la base de datos
mortalidad=pd.read_csv('mortalidad.csv')
pd.DataFrame(mortalidad)

# Ver lista completa
mortalidad

Año de nacimiento  Mes de nacimiento Descripción del mes de nacimiento  \
0                   1972                  6                             JUNIO   
1                   1967                  2                           FEBRERO   
2                   1973                  6                             JUNIO   
3                   1966                  1                             ENERO   
4                   1975                  0                   NO ESPECIFICADO   
5                   1975                  0                   NO ESPECIFICADO   
6                   1985                  0                   NO ESPECIFICADO   
7                   1978                  7                             JULIO   
8                   1958                  9                        SEPTIEMBRE   
9                   1970                  5                              MAYO   
10                  1972                  4                             ABRIL   
11                  1966                  1                             ENERO   
12                  1969                  0                   NO ESPECIFICADO   
13                  1973                  0                   NO ESPECIFICADO   
14                  1960                  4                             ABRIL   
15                  1963                  2                           FEBRERO   
16                  1988                  0                   NO ESPECIFICADO   
17                  1978                  0                   NO ESPECIFICADO   
18                  1974                  0                   NO ESPECIFICADO   
19                  1970                  8                            AGOSTO   
20                  1974                  2                           FEBRERO   
21                  1977                  5                              MAYO   
22                  1983                  4                             ABRIL   
23                  1992                  3                             MARZO   
24                  1989                  3                             MARZO   
25                  1987                  9                        SEPTIEMBRE   
26                  1966                  9                        SEPTIEMBRE   
27                  1968                 10                           OCTUBRE   
28                  1985                  0                   NO ESPECIFICADO   
29                  1971                  8                            AGOSTO   
...                  ...                ...                               ...   
17202               1990                 12                         DICIEMBRE   
17203               1977                  8                            AGOSTO   
17204               1988                 11                         NOVIEMBRE   
17205               1986                  1                             ENERO   
17206               1985                  2                           FEBRERO   
17207               1982                  8                            AGOSTO   
17208               1986                  5                              MAYO   
17209               1999                  7                             JULIO   
17210               1982                  3                             MARZO   
17211               2000                  8                            AGOSTO   
17212               1989                  9                        SEPTIEMBRE   
17213               1995                 10                           OCTUBRE   
17214               1984                 12                         DICIEMBRE   
17215               1995                  4                             ABRIL   
17216               1990                  8                            AGOSTO   
17217               1988                  9                        SEPTIEMBRE   
17218               1992                 10                           OCTUBRE   
17219               1987              

In [75]:
#Nombre de los encabezados
mortalidad.head()


Año de nacimiento  Mes de nacimiento Descripción del mes de nacimiento  \
0               1972                  6                             JUNIO   
1               1967                  2                           FEBRERO   
2               1973                  6                             JUNIO   
3               1966                  1                             ENERO   
4               1975                  0                   NO ESPECIFICADO   

   Día de nacimiento  Genero Clave de la edad  Edad cumplida  Estado conyugal  \
0                 25       2                A             29                5   
1                  1       2                A             35                5   
2                 21       2                A             29                5   
3                 23       2                A             36                5   
4                  0       2                A             30                5   

  Descripción del estado conyugal  Entidad de residencia  \
0                          CASADO                     31   
1                          CASADO                     31   
2                          CASADO                     31   
3                          CASADO                     31   
4                          CASADO                      9   

                         ...                         Mes de registro  \
0                        ...                                       1   
1                        ...                                       7   
2                        ...                                      10   
3                        ...                                      10   
4                        ...                                       4   

   Descripción del mes de registro Día de registro  Año de la certificación  \
0                            ENERO              20                      NaN   
1                            JULIO              28                      NaN   
2                          OCTUBRE              24                      NaN   
3                          OCTUBRE              20                      NaN   
4                            ABRIL               8                   2005.0   

  Mes de la certificación  Descripció del mes de la certificación  \
0                       0                         NO ESPECIFICADO   
1                       0                         NO ESPECIFICADO   
2                       0                         NO ESPECIFICADO   
3                       0                         NO ESPECIFICADO   
4                       4                                   ABRIL   

  Día de la certificación  Año de la base de datos  \
0                     NaN                     2002   
1                     NaN                     2002   
2                     NaN                     2002   
3                     NaN                     2002   
4                     8.0                     2005   

  Razón de mortalidad materna  \
0                           1   
1                           1   
2                           1   
3                           1   
4                           1   

        Descrición de la razón de mortalidad materna  
0  Muertes Maternas para la razón de Mortalidad M...  
1  Muertes Maternas para la razón de Mortalidad M...  
2  Muertes Maternas para la razón de Mortalidad M...  
3  Muertes Maternas para la razón de Mortalidad M...  
4  Muertes Maternas para la razón de Mortalidad M...  

[5 rows x 58 columns]

In [111]:
# Borrar columnas con el método drop
# Crear copia en este caso es: mortalidad es la copia 
mortalidad1=mortalidad.drop(['Año de nacimiento', 'Mes de nacimiento', 'Descripción del mes de nacimiento', 'Día de nacimiento', 'Genero', 'Clave de la edad', 'Estado conyugal', 'Entidad de residencia', 'Mes de registro', 'Descripción del mes de registro', 'Día de registro', 'Año de la certificación', 'Mes de la certificación', 'Descripción del mes de la certificación', 'Día de la certificación'],axis=1) 


KeyError: "['Descripción del mes de la certificación'] not found in axis"

In [113]:
# Ver los datos borrados
pd.DataFrame(mortalidad1)

Edad cumplida Descripción del estado conyugal  \
0                 29                          CASADO   
1                 35                          CASADO   
2                 29                          CASADO   
3                 36                          CASADO   
4                 30                          CASADO   
5                 30                          CASADO   
6                 20                          CASADO   
7                 27                          CASADO   
8                 43                          CASADO   
9                 31                          CASADO   
10                31                          CASADO   
11                35                          CASADO   
12                39                          CASADO   
13                29                          CASADO   
14                45                          CASADO   
15                42                          CASADO   
16                17                          CASADO   
17                35                          CASADO   
18                39                       SE IGNORA   
19                43                          CASADO   
20                38                          CASADO   
21                36                          CASADO   
22                26                          CASADO   
23                17                          CASADO   
24                21                          CASADO   
25                22                          CASADO   
26                45                          CASADO   
27                43                          CASADO   
28                26                          CASADO   
29                40                          CASADO   
...              ...                             ...   
17202             25                         SOLTERO   
17203             39                          CASADO   
17204             27                          CASADO   
17205             30                     UNION LIBRE   
17206             31                          CASADO   
17207             33                          CASADO   
17208             30                          CASADO   
17209             16                         SOLTERO   
17210             34                           VIUDO   
17211             16                     UNION LIBRE   
17212             26                     UNION LIBRE   
17213             21                     UNION LIBRE   
17214             32                          CASADO   
17215             21                         SOLTERO   
17216             25                     UNION LIBRE   
17217             27                     UNION LIBRE   
17218             23                     UNION LIBRE   
17219             29                          CASADO   
17220             16                         SOLTERO   
17221             27                     UNION LIBRE   
17222             27                     UNION LIBRE   
17223             37                          CASADO   
17224             26                         SOLTERO   
17225             23                     UNION LIBRE   
17226             27                         SOLTERO   
17227             20                         SOLTERO   
17228             45                          CASADO   
17229             21                         SOLTERO   
17230             39                          CASADO   
17231             25                          CASADO   

      Descripción de entidad de residencia  Municipio de residencia  \
0                                  Yucatán                      102   
1                                  Yucatán                       96   
2                                  Yucatán                       62   
3                                  Yucatán                       60   
4                         Distrito Federal                        7   
5                         Distrito Federal                       14   
6                                   M

In [90]:
# ¿Cuántas edades diferentes tenían las madres cuando fallecieron? Obten los estadísticos para esta columna y los valores de las edades diferentes. 
mortalidad1["Edad cumplida"].unique()

array([ 29,  35,  36,  30,  20,  27,  43,  31,  39,  45,  42,  17,  38,
        26,  21,  22,  40,  44,  34,  41,  33,  13,  24,  25,  37,  19,
        23,  32,  28, 998,  15,  46,  48,  16,  18,  12,  47,  14,  51,
        50,  54,  49,  11,  53,  81,  70,  82,  59,  86,  65], dtype=int64)

In [79]:
# Imprime los valores de los años de defunción ¿ Existen datos que son lógicos, es decir, están correctos?

mortalidad1["Año de la defunción"].unique()

array([2002, 2005, 2003, 2008, 2013, 2012, 2009, 2010, 2011, 2004, 2006,
       2007, 2001, 1979, 1989, 1974, 1964, 1982, 1959, 1990, 1980, 1994,
       1977, 1976, 1938, 1970, 1949, 1997, 1956, 1961, 1957, 1985, 1975,
       2000,    0, 1948, 1971, 1978, 1984, 1993, 1992, 1972, 1973, 1986,
       1988, 1937, 1965, 1944, 1987, 1943, 1958, 1967, 1968, 1995, 1991,
       1969, 1999, 1966, 1963, 1953, 1954, 1962, 1950, 1996, 2014, 2015,
       1914, 1951, 2016], dtype=int64)

In [81]:
# ¿Cuántos tipos de escolaridad existen? ¿Hay datos innecesarios o equivocados en la base de datos?
mortalidad["Escolaridad"].unique()

array([ 2,  4,  7,  1,  5,  0, 10,  3,  6, 11, 12], dtype=int64)